name: 10
timestamp: 1591526639
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1591526639
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-4607: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-4739: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-9082: Copyright
  social:
    social-2298: Social
  branding:
    branding-3160: Branding
  mobile-menu:
    mobile-menu-4592: 'Mobile Menu'
inherit: {  }
