version: '2'
services: 
  joomla:
    image: joomla
    ports:
     - "8001:80"
    environment:
     - JOOMLA_DB_HOST=<mysql>:3306
     - JOOMLA_DB_PASSWORD_ALLOW_EMPTY=yes
     - JOOMLA_DB_USER=root
    volumes:
     - ./code:/var/www/html
