name: '9'
timestamp: 1591526639
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1591526639
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4743: Logo
    logo-8835: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
    position-position-6243: Header
    position-position-2309: Breadcrumbs
    position-position-7559: Footer
  menu:
    menu-6380: Menu
    menu-2400: Menu
  messages:
    system-messages-2598: 'System Messages'
    system-messages-3960: 'System Messages'
  content:
    system-content-4570: 'Page Content'
    system-content-5738: 'Page Content'
  copyright:
    copyright-1692: Copyright
    copyright-5001: Copyright
  spacer:
    spacer-9178: Spacer
    spacer-3037: Spacer
  branding:
    branding-9530: Branding
    branding-5898: Branding
  mobile-menu:
    mobile-menu-8535: Mobile-menu
    mobile-menu-8271: Mobile-menu
inherit:
  default:
    header: header
    logo-4743: logo-4743
    position-header: position-header
    navigation: navigation
    menu-6380: menu-6380
    main: main
    position-breadcrumbs: position-breadcrumbs
    system-messages-2598: system-messages-2598
    system-content-4570: system-content-4570
    footer: footer
    position-footer: position-footer
    copyright-1692: copyright-1692
    spacer-9178: spacer-9178
    branding-9530: branding-9530
    offcanvas: offcanvas
    mobile-menu-8535: mobile-menu-8535
    logo-8835: logo-4743
    position-position-6243: position-header
    menu-2400: menu-6380
    position-position-2309: position-breadcrumbs
    system-messages-3960: system-messages-2598
    system-content-5738: system-content-4570
    position-position-7559: position-footer
    copyright-5001: copyright-1692
    spacer-3037: spacer-9178
    branding-5898: branding-9530
    mobile-menu-8271: mobile-menu-8535
